name: Build DEB and RPM

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y rpm dpkg-dev

      - name: Build DEB package
        run: |
          mkdir -p build-deb
          cp -r DEBIAN usr build-deb/
          dpkg-deb --build build-deb countfiles.deb

      - name: Prepare RPM build tree
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp usr/local/bin/count_files.sh ~/rpmbuild/SOURCES/
          cp rpm/count-etc-files.spec ~/rpmbuild/SPECS/

      - name: Build RPM package
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/count-etc-files.spec

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: countfiles.deb

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: ~/rpmbuild/RPMS/**/**/*.rpm
